//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.CopySeries {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class CopySeriesIntoShareAtSourceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CopySeriesIntoShareAtSourceSettings defaultInstance = ((CopySeriesIntoShareAtSourceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CopySeriesIntoShareAtSourceSettings())));
        
        public static CopySeriesIntoShareAtSourceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Videos")]
        public string TargetDir {
            get {
                return ((string)(this["TargetDir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Download")]
        public string SourceDir {
            get {
                return ((string)(this["SourceDir"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S:\\")]
        public string StickDrive {
            get {
                return ((string)(this["StickDrive"]));
            }
            set {
                this["StickDrive"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Tools")]
        public string ToolsDir {
            get {
                return ((string)(this["ToolsDir"]));
            }
        }
    }
}
